title: "Performance vs number of tasks and CPUs_per_task"

x_axis:
  value: "tasks"
  units:
    custom: null

y_axis:
  value: "flops_value"
  units:
    column: "flops_unit"

series: [["cpus_per_task", "1"], ["cpus_per_task", "2"]]

# Commented-out lines are for use with the dirtier example perflog
# in the tutorial folder
#filters: [["tags", "==", "example"]]
filters: []

column_types:
  tasks: "int"
  flops_value: "float"
  flops_unit: "str"
  cpus_per_task: "int"
#  tags: "str"
